import { Optional } from "../../types";
import { NameValuePair } from "../dto/NameValuePair";
import { BaseApplicationConfiguration } from "./BaseApplicationConfiguration";
import { ImageSavingConvention } from "./ImageSavingConvention";
import { MetadataOptions } from "./MetadataOptions";
import { PathSubstitution } from "./PathSubstitution";

export interface ServerConfiguration extends BaseApplicationConfiguration {
    EnableUPnP: boolean;
    PublicPort: number;
    PublicHttpsPort: number;
    HttpServerPortNumber: number;
    HttpsPortNumber: number;
    EnableHttps: boolean;
    EnableNormalizedItemByNameIds: boolean;
    CertificatePath: Optional<string>;
    CertificatePassword: Optional<string>;
    IsPortAuthorized: boolean;
    AutoRunWebApp: boolean;
    EnableRemoteAccess: boolean;
    CameraUploadUpgraded: boolean;
    CollectionsUpgraded: boolean;
    EnableCaseSensitiveItemIds: boolean;
    DisableLiveTvChannelUserDataName: boolean;
    MetadataPath: Optional<string>;
    MetadataNetworkPath: Optional<string>;
    PreferredMetadataLanguage: Optional<string>;
    MetadataCountryCode: Optional<string>;
    SortReplaceCharacters: string[];
    SortRemoveCharacters: string[];
    SortRemoveWords: string[];
    MinResumePct: number;
    MaxResumePct: number;
    MinResumeDurationSeconds: number;
    LibraryMonitorDelay: number;
    EnableDashboardResponseCaching: boolean;
    DashboardSourcePath: Optional<string>;
    ImageSavingConvention: ImageSavingConvention;
    MetadataOptions: MetadataOptions[];
    SkipDeserializationForBasicTypes: boolean;
    ServerName: Optional<string>;
    BaseUrl: Optional<string>;
    UICulture: Optional<string>;
    SaveMetadataHidden: boolean;
    ContentTypes: NameValuePair[];
    RemoteClientBitrateLimit: number;
    EnableFolderView: boolean;
    EnableGroupingIntoCollections: boolean;
    DisplaySpecialsWithinSeasons: boolean;
    LocalNetworkSubnets: string[];
    LocalNetworkAddresses: string[];
    CodecsUsed: string[];
    IgnoreVirtualInterfaces: boolean;
    EnableExternalContentInSuggestions: boolean;
    RequireHttps: boolean;
    IsBehindProxy: boolean;
    EnableNewOmdbSupport: boolean;
    RemoteIPFilter: string[];
    IsRemoteIPFilterBlacklist: boolean;
    ImageExtractionTimeoutMs: number;
    PathSubstitutions: PathSubstitution[];
    EnableSimpleArtistDetection: boolean;
    UninstalledPlugins: string[];
}
