import { Optional } from "../../types";
import { SubtitleDeliveryMethod } from "../dlna/SubtitleDeliveryMethod";
import { MediaStreamType } from "./MediaStreamType";

export interface MediaStream {
    Codec: Optional<string>;
    CodecTag: Optional<string>;
    Language: Optional<string>;
    ColorTransfer: Optional<string>;
    ColorPrimaries: Optional<string>;
    ColorSpace: Optional<string>;
    Comment: Optional<string>;
    TimeBase: Optional<string>;
    CodecTimeBase: Optional<string>;
    Title: Optional<string>;
    VideoRange: Optional<string>;
    localizedUndefined: Optional<string>;
    localizedDefault: Optional<string>;
    localizedForced: Optional<string>;
    DisplayTitle: Optional<string>;
    NalLengthSize: Optional<string>;
    IsInterlaced: boolean;
    IsAVC: Optional<boolean>;
    ChannelLayout: Optional<string>;
    BitRate: Optional<number>;
    BitDepth: Optional<number>;
    RefFrames: Optional<number>;
    PacketLength: Optional<number>;
    Channels: Optional<number>;
    SampleRate: Optional<number>;
    IsDefault: boolean;
    IsForced: boolean;
    Height: Optional<number>;
    Width: Optional<number>;
    AverageFrameRate: Optional<number>;
    RealFrameRate: Optional<number>;
    Profile: Optional<string>;
    Type: MediaStreamType;
    AspectRatio: Optional<string>;
    Index: number;
    Score: Optional<number>;
    IsExternal: boolean;
    DeliveryMethod: Optional<SubtitleDeliveryMethod>;
    DeliveryUrl: Optional<string>;
    IsExternalUrl: Optional<boolean>;
    IsTextSubtitleStream: boolean;
    SupportsExternalStream: boolean;
    Path: Optional<string>;
    PixelFormat: Optional<string>;
    Level: Optional<number>;
    IsAnamorphic: Optional<boolean>;
}
