name: Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup node environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node_modules
        uses: actions/cache@v2.1.6
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: npm run build
